Update 1.3.0

diff --git a/nva b/nva
--- a/nva
+++ b/nva
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-nva_version="1.2.0"
+nva_version="1.3.0"
 
 # Get the directory of the script, resolving symbolic links
 script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
@@ -11,6 +11,7 @@ cleanup="false"
 install_version=""
 set_version=""
 remove_version=""
+all_versions=$(curl -s https://nodejs.org/download/release/ | grep -oP '^<a href="v\K\d+\.\d+\.\d+' | uniq | sort -V)
 
 if [ ! -d "$node_versions_dir" ]; then
     if [ -w "$script_dir" ]; then
@@ -23,9 +24,9 @@ if [ ! -d "$node_versions_dir" ]; then
     fi
 fi
 
-check_node_version(){
+check_running_node_version(){
     if [ -n "$(command -v node)" ]; then
-        current_version=$(node --version | grep -oP '\d.*')
+        running_version=$(node --version | grep -oP '\d.*')
     fi
 }
 
@@ -42,9 +43,8 @@ Options:
 
   -s, --set            Set the active Node.js version
 
-  -p, --patch          Update all installed Node.js versions to the latest
-                       Subcommands:
-                       clean: Remove all old Node.js versions
+  -p, --patch          Update all installed Node.js versions to the latest patch.
+                       This automatically removes old versions and updates the patch number.
 
   -r, --remove         Remove an installed Node.js version
 
@@ -65,6 +65,10 @@ install() {
     else
         if [ -w "$node_versions_dir" ]; then
             local response_code=$(curl -sLI "https://nodejs.org/download/release/v$install_version/" | grep -i "^HTTP" | awk '{print $2}')
+            if [ $? -ne 0 ] || [ -z "$response_code" ]; then
+                echo "Error -i|--install: no connection to https://nodejs.org/download/release/"
+                exit 1
+            fi
             if [ "$response_code" -eq 200 ]; then
                 curl -sL "https://nodejs.org/download/release/v$install_version/node-v$install_version-linux-x64.tar.xz" -o "$node_versions_dir/node-v$install_version-linux-x64.tar.xz"
                 if [ $? -eq 0 ]; then
@@ -78,27 +82,31 @@ install() {
                         echo "Node.js version $install_version extracted successfully"
                         rm -r "$node_versions_dir/node-v$install_version-linux-x64.tar.xz"
                     else
-                        echo "Failed to extract Node.js version $install_version"
+                        echo "-i|--install Failed to extract Node.js version $install_version"
+                        exit 1
                     fi
                 else
-                    echo "Failed to download Node.js version $install_version"
+                    echo "-i|--install Failed to download Node.js version $install_version"
+                    exit 1
                 fi
             else 
-                echo "The version $install_version doesn't exist"
+                echo "-i|--install The version $install_version doesn't exist"
+                exit 1
             fi
         else
-            echo "Error: You don't have permission"
+            echo "Error -i|--install: You don't have permission"
+            exit 1
         fi
     fi
 }
 
 list(){
-    check_node_version
+    check_running_node_version
     local local_versions=$(find "$node_versions_dir" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | grep -oP '\d+(\.\d+){0,2}')
     if [ -n "$local_versions" ]; then
     echo "Available Node.js versions installed on your system:"
     for version in $local_versions; do
-            if [ "$current_version" = "$version" ]; then
+            if [ "$running_version" = "$version" ]; then
                 echo "* Node.js $version (Running)"
             else
                 echo "  Node.js $version"
@@ -106,7 +114,9 @@ list(){
         done
     else
         echo "No Node.js versions found in $node_versions_dir."
-        echo "You may want to install some using the nva script."
+        echo "You may want to install Node.js using the nva script."
+        echo -e "nva --install <node_version>\n"
+        exit 1
     fi
 
 }
@@ -120,103 +130,107 @@ set_nodejs(){
             npm config set prefix /usr/local -g
             echo "Node.js version $set_version has been set successfully."
         else
-            echo "Error: Insufficient privileges. Please run with sudo."
+            echo "Error -s|--set: Insufficient privileges. Please run with sudo."
             exit 1
         fi
     else
-        echo "Error: Node.js version $set_version does not exist in your system."
+        echo "Error -s|--set: Node.js version $set_version does not exist in your system."
         exit 1
     fi
 }
 
 remove() {
-    check_node_version
-    if [ -e "$node_versions_dir/$set_version" ]; then
-        if [ "$remove_version" != "$current_version" ]; then
+    check_running_node_version
+
+    # If wildcard is used
+    if [[ "$remove_version" == *"*"* ]]; then
+        local matches=($(find "$node_versions_dir" -maxdepth 1 -type d -printf '%f\n' | grep -E "^${remove_version//\*/.*}$"))
+        
+        if [ ${#matches[@]} -eq 0 ]; then
+            echo "Error -r|--remove: No versions match the pattern '$remove_version'."
+            exit 1
+        fi
+
+        for match in "${matches[@]}"; do
+            if [ "$match" == "$running_version" ]; then
+                echo "Skipping currently running version: $match"
+                continue
+            fi
+
+            if [ -w "$node_versions_dir/$match" ]; then
+                rm -rf "$node_versions_dir/$match"
+                echo "Removed: $match"
+            else
+                echo "Error -r|--remove: No permission to remove $match"
+            fi
+        done
+        return
+    fi
+
+    # If exact version is given
+    if [ -e "$node_versions_dir/$remove_version" ]; then
+        if [ "$remove_version" != "$running_version" ]; then
             if [ -w "$node_versions_dir/$remove_version" ]; then
                 rm -rf "$node_versions_dir/$remove_version"
-                echo "Success: Node.js version $remove_version has been removed."
+                echo "Node.js version $remove_version has been removed."
             else
-                echo "Error: You do not have permission to remove Node.js version $remove_version."
+                echo "Error -r|--remove: You do not have permission to remove Node.js version $remove_version."
                 echo "Check file permissions and try again or run with elevated privileges."
             fi
         else
             echo "Info: Cannot remove the currently running Node.js version."
-            echo "Use 'nva -s <other_version>' to set another version before removing the running version."
+            echo "Use 'nva --set <node_version>' to set another version before removing the running version."
         fi
     else
-        echo "Error: The specified Node.js version ($remove_version) does not exist."
+        echo "Error -r|--remove: The specified Node.js version ($remove_version) does not exist."
         exit 1
     fi
 }
 
+# Update the version patch in the format MAJOR.MINOR.PATCH so that only the patch number is updated for example, from 24.4.0 to 24.4.1
 patch(){
-    check_node_version
+    check_running_node_version
     echo "#### Running Patch ####"
-    local count_updates=0
-    local major_current_version=$(echo $current_version | grep -oP '^\d+')
+    if [ $? -ne 0 ] || [ -z "$all_versions" ]; then
+        echo "Error -p|--patch: no connection or failed to fetch versions"
+        exit 1
+    fi
 
-    local new_versions=$(curl -s https://nodejs.org/en/download/releases | grep -oP '<td.*?>Node\.js\s*<!--.*?-->\K\d+(\.\d+){0,2}' | grep -v '^$')
-
-    local local_versions=$(find "$node_versions_dir" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | grep -oP '^\d+')
-
-    local updates=()
-
-    # Check for updates by using the major version number 
-    for new_version in $new_versions; do 
-        major_new_version=$(echo $new_version | awk -F'.' '{print $1}')
-        for version in $local_versions; do
-            if [ "$major_new_version" = "$version" ]; then
-                updates+=("$new_version")
-            fi
-            if [ "$major_new_version" = "$major_current_version" ]; then
-                set_version="$new_version"
-            fi
-        done
-    done
-
-    # Remove duplicates
-    local new_nodejs_dir=($(echo "${updates[@]}" | tr ' ' '\n' | awk '!seen[$0]++' | tr '\n' ' '))
-
-    for install in "${new_nodejs_dir[@]}"; do
-        if [ -e "$node_versions_dir/$install" ]; then
-            continue
-        else
-            install_version=$install
+    local installed_versions=($(find "$node_versions_dir" -maxdepth 1 -mindepth 1 -type d -exec basename {} \;))
+    for version in "${installed_versions[@]}"; do
+        local strip_version=$(echo "$version" | grep -oP '^\d+\.\d+')
+        local check_patch_version=$(echo "$all_versions" | tr ' ' '\n' | grep -oP "^${strip_version}\.\d+" | tail -n 1)
+        if [ "$version" != "$check_patch_version" ]; then
+            echo "Need update: $version → $check_patch_version"
+            install_version=$check_patch_version
             install
-            count_updates+=1
-        fi
-    done 
-
-    if  [ -n "$set_version" ] && [ "$current_version" != "$set_version" ]; then
-        set_nodejs
-    fi
-
-    if [ "$cleanup" = "true" ]; then
-        # Cleanup step: Remove directories that are no longer needed
-        local local_versions=$(find "$node_versions_dir" -maxdepth 1 -mindepth 1 -type d -exec basename {} \; | grep -oP '\d+(\.\d+){0,2}')
-        local unique_elements=($(comm -23 <(printf "%s\n" "${local_versions[@]}" | sort -u) <(printf "%s\n" "${new_nodejs_dir[@]}" | sort -u)))
-        for element in "${unique_elements[@]}"; do
-            if [ -d "$node_versions_dir/$element" ]; then
-                rm -rf "$node_versions_dir/$element"
-                echo "Removed directory: $element"
+            if [ $? -ne 1 ]; then
+                if [ "$version" == "$running_version" ]; then
+                    set_version=$check_patch_version
+                    set_nodejs
+                fi
+                remove_version=$version
+                remove
             fi
-        done
-    fi
-
-    if [ $count_updates -gt 0 ]; then
-        echo "#### Finished Patch - Updates Applied ####"
-    else
-        echo "#### Finished Patch - Everything is Up to Date ####"
-    fi
-
+        fi
+    done
 }
+
+
+if [ $# -eq 0 ]; then
+    print_help
+    exit 0
+fi
 
 while [[ $# -gt 0 ]]; do
     case "$1" in
         -i|--install)
             if [ -n "$2" ]; then
-                install_version="$2"
+                if [ "$2" = "latest" ]; then
+                    install_version=$(echo "$all_versions" | tail -n 1)
+                else 
+                    install_version="$2"
+                fi 
                 install
                 shift 2
             else
@@ -226,7 +240,11 @@ while [[ $# -gt 0 ]]; do
             ;;
         -s|--set)
             if [ -n "$2" ]; then
-                set_version="$2"
+                if [ "$2" = "latest" ]; then
+                        set_version=$(echo "$all_versions" | tail -n 1)
+                    else 
+                        set_version="$2"
+                fi 
                 set_nodejs
                 shift 2
             else
@@ -240,7 +258,7 @@ while [[ $# -gt 0 ]]; do
                 remove
                 shift 2
             else
-                echo "Error: -s/--set option requires a version parameter"
+                echo "Error: -r/--remove option requires a version parameter"
                 exit 2
             fi
             ;;
@@ -249,18 +267,8 @@ while [[ $# -gt 0 ]]; do
             shift
             ;;
         -p|--patch)
-           if [ "$2" = "clean" ]; then
-                cleanup="true"
-                patch
-                shift 2
-            elif [ -z "$2" ]; then
-                patch
-                shift
-            else 
-                echo "Error: Unrecognized parameter '$2'."
-                echo "Usage: nva -p clean"
-                exit 2
-            fi
+            patch
+            shift
             ;;
         -v|--version)
             print_version
@@ -271,9 +279,10 @@ while [[ $# -gt 0 ]]; do
             exit 0
             ;;
         *)
-            echo "Unknown option: $1"
+            echo "Error: Unknown option '$1'"
             print_help
             exit 1
             ;;
     esac
 done
+
